export type CatalogProduct = {
  id: string;
  name: string;
  oneLiner: string;
  keywords: string[];
  fallbackKeywords?: string[];
  formatHints: string[];
  pricingHints?: { trial: [number, number]; monthly: [number, number]; bundle: [number, number] };
};

export const CATALOG: Record<string, CatalogProduct[]> = {
  "Wellness & Supplements": [
    { id: "postbiotic-gut-barrier-micro-pellets", name: "Postbiotic \"Gut Barrier\" Micro-Pellets", oneLiner: "Gut support in a precise micro-pellet format.", keywords: ["postbiotic supplement india", "gut barrier postbiotic", "postbiotic micro pellets"], fallbackKeywords: ["gut barrier postbiotic", "postbiotic micro pellets"], formatHints: ["micro-pellets", "capsules", "sachets"], pricingHints: { trial: [299, 499], monthly: [899, 1499], bundle: [2299, 3499] } },
    { id: "electrolyte-mineral-heat-shield-capsules", name: "Electrolyte Mineral \"Heat Shield\" Capsules", oneLiner: "Mineral-first summer hydration support.", keywords: ["electrolyte mineral capsules", "heat hydration capsules india", "potassium magnesium summer supplement"], fallbackKeywords: ["heat hydration capsules india", "potassium magnesium summer supplement"], formatHints: ["capsules", "effervescent tabs", "sachets"], pricingHints: { trial: [199, 349], monthly: [699, 1199], bundle: [1699, 2899] } },
    { id: "sleep-stack-strip-films", name: "Sleep Stack Strip-Films (Glycine + L-theanine)", oneLiner: "Fast bedtime strips for calmer sleep onset.", keywords: ["sleep strip film glycine", "l theanine strip sleep", "melatonin free sleep strips"], fallbackKeywords: ["l theanine strip sleep", "melatonin free sleep strips"], formatHints: ["strip-films", "sachets", "gummies"], pricingHints: { trial: [249, 399], monthly: [799, 1399], bundle: [1999, 3199] } },
    { id: "protein-compliance-mini-shots", name: "Protein Compliance Mini-Shots (10-15g)", oneLiner: "Small shots for daily protein consistency.", keywords: ["protein mini shots", "10g protein shot india", "small protein drink low sugar"], fallbackKeywords: ["10g protein shot india", "small protein drink low sugar"], formatHints: ["mini-shots", "rtd bottles", "powder sticks"], pricingHints: { trial: [149, 299], monthly: [1199, 2199], bundle: [2799, 4499] } },
    { id: "stress-reset-patch-pack", name: "Stress Reset \"Patch\" Pack (wearable calm patch bundle)", oneLiner: "Wearable calm support during high-stress hours.", keywords: ["calm patch wearable", "stress relief patch india", "anxiety patch non cbd"], fallbackKeywords: ["stress relief patch india", "anxiety patch non cbd"], formatHints: ["patches", "kits", "strips"], pricingHints: { trial: [299, 499], monthly: [999, 1799], bundle: [2499, 3899] } },
    { id: "womens-iron-energy-week-kit", name: "Women's Iron + Energy \"Week Kit\" (day-by-day sachets)", oneLiner: "Structured weekly fatigue reset for women.", keywords: ["womens iron sachet kit", "fatigue reset women supplement", "iron b12 week kit"], fallbackKeywords: ["fatigue reset women supplement", "iron b12 week kit"], formatHints: ["week kits", "sachets", "capsules"], pricingHints: { trial: [349, 599], monthly: [1299, 2199], bundle: [2999, 4599] } },
    { id: "anti-bloat-enzyme-chews", name: "Anti-Bloat Enzyme Chews (Indian meals)", oneLiner: "Meal-time enzyme chews for post-meal comfort.", keywords: ["anti bloat enzyme chews", "digestive enzyme chew india", "after meal bloating supplement"], fallbackKeywords: ["digestive enzyme chew india", "after meal bloating supplement"], formatHints: ["chews", "tablets", "sachets"], pricingHints: { trial: [199, 349], monthly: [699, 1299], bundle: [1699, 2799] } },
    { id: "creatine-cognition-sachets-women", name: "Creatine \"Cognition\" Sachets (Women)", oneLiner: "Creatine with strength + mental performance positioning.", keywords: ["creatine cognition women", "creatine sachet women india", "women creatine brain performance"], fallbackKeywords: ["creatine sachet women india", "women creatine brain performance"], formatHints: ["sachets", "gummies", "capsules"], pricingHints: { trial: [249, 399], monthly: [899, 1499], bundle: [2199, 3499] } },
  ],
  "Functional Beverages": [
    { id: "gut-soda-2-postbiotic-sparkling", name: "Gut Soda 2.0 (Postbiotic Sparkling)", oneLiner: "Soda-like experience with gut-friendly positioning.", keywords: ["postbiotic sparkling drink", "gut soda india", "low sugar gut soda"], fallbackKeywords: ["gut soda india", "low sugar gut soda"], formatHints: ["soda", "shots", "mix sachet"], pricingHints: { trial: [89, 149], monthly: [999, 1899], bundle: [2199, 3999] } },
    { id: "sleep-cocoa-magnesium-glycine", name: "Sleep Cocoa (Magnesium + Glycine hot mix)", oneLiner: "Night hot mix for wind-down routines.", keywords: ["sleep cocoa magnesium", "glycine hot drink sleep", "bedtime magnesium drink mix"], fallbackKeywords: ["glycine hot drink sleep", "bedtime magnesium drink mix"], formatHints: ["hot mix sachet", "jar mix", "single sticks"], pricingHints: { trial: [199, 349], monthly: [799, 1399], bundle: [1899, 3199] } },
    { id: "electrolyte-ice-pop-sticks", name: "Electrolyte \"Ice Pop\" Hydration Sticks", oneLiner: "Fun hydration format for summer + workouts.", keywords: ["electrolyte ice pop", "hydration stick india", "summer electrolyte sticks"], fallbackKeywords: ["hydration stick india", "summer electrolyte sticks"], formatHints: ["sticks", "sachets", "shots"], pricingHints: { trial: [149, 249], monthly: [699, 1199], bundle: [1599, 2799] } },
    { id: "protein-lassi-rtd-low-sugar", name: "Protein Lassi RTD (Low Sugar)", oneLiner: "India-native protein RTD with lower sugar.", keywords: ["protein lassi low sugar", "lassi protein drink india", "high protein lassi rtd"], fallbackKeywords: ["lassi protein drink india", "high protein lassi rtd"], formatHints: ["rtd bottle", "tetra pack", "shot"], pricingHints: { trial: [79, 129], monthly: [1299, 2199], bundle: [2999, 4999] } },
    { id: "focus-tonic-caffeine-free-sparkling", name: "Focus Tonic (Caffeine-Free) Sparkling", oneLiner: "Focus drink without caffeine jitters.", keywords: ["caffeine free focus drink", "l theanine tyrosine sparkling", "focus tonic india"], fallbackKeywords: ["l theanine tyrosine sparkling", "focus tonic india"], formatHints: ["sparkling", "shots", "mix sachet"], pricingHints: { trial: [99, 159], monthly: [1199, 1999], bundle: [2699, 4399] } },
    { id: "skin-drink-ceramide-support", name: "Collagen-Free \"Skin Drink\" (Ceramide support)", oneLiner: "Ingestible skin hydration without collagen claims.", keywords: ["ceramide skin drink", "collagen free skin drink", "skin barrier drink india"], fallbackKeywords: ["collagen free skin drink", "skin barrier drink india"], formatHints: ["rtd", "shots", "powder sticks"], pricingHints: { trial: [119, 199], monthly: [1299, 2299], bundle: [3099, 5199] } },
    { id: "spice-digestion-shot", name: "Spice Digestion Shot (Jeera/Fennel + science angle)", oneLiner: "Digestive spice shot with modern formulation.", keywords: ["jeera fennel digestion shot", "digestive shot india", "post meal digestion drink"], fallbackKeywords: ["digestive shot india", "post meal digestion drink"], formatHints: ["shots", "soda", "mix sachet"], pricingHints: { trial: [69, 129], monthly: [899, 1599], bundle: [1999, 3499] } },
    { id: "glucose-friendly-chaas", name: "Glucose-Friendly Chaas (Metabolic hydration)", oneLiner: "Low-glycemic chaas for daily hydration.", keywords: ["glucose friendly chaas", "low sugar chaas drink", "metabolic hydration drink india"], fallbackKeywords: ["low sugar chaas drink", "metabolic hydration drink india"], formatHints: ["rtd", "powder mix", "concentrate"], pricingHints: { trial: [79, 139], monthly: [999, 1799], bundle: [2299, 3899] } },
  ],
  "Beauty & Personal Care": [
    { id: "scalp-microbiome-mist", name: "Scalp Microbiome Mist (Hair fall)", oneLiner: "Daily scalp mist for hair-fall support.", keywords: ["scalp microbiome mist", "hair fall scalp spray", "prebiotic scalp care india"], fallbackKeywords: ["hair fall scalp spray", "prebiotic scalp care india"], formatHints: ["mist", "serum", "spray"], pricingHints: { trial: [299, 499], monthly: [899, 1699], bundle: [2199, 3899] } },
    { id: "barrier-sunscreen-drops", name: "Barrier Sunscreen Drops (Mix-in)", oneLiner: "Add-on sunscreen drops with barrier focus.", keywords: ["barrier sunscreen drops", "mix in sunscreen drops", "ceramide sunscreen drops"], fallbackKeywords: ["mix in sunscreen drops", "ceramide sunscreen drops"], formatHints: ["drops", "serum", "stick"], pricingHints: { trial: [349, 599], monthly: [999, 1899], bundle: [2499, 4299] } },
    { id: "body-acne-after-gym-spray", name: "Body Acne \"After-Gym\" Spray", oneLiner: "Quick post-workout acne body spray.", keywords: ["body acne spray after gym", "back acne spray india", "salicylic body spray"], fallbackKeywords: ["back acne spray india", "salicylic body spray"], formatHints: ["spray", "mist", "serum"], pricingHints: { trial: [299, 499], monthly: [899, 1499], bundle: [2099, 3499] } },
    { id: "underarm-care-serum", name: "Underarm Care Serum (Odor + Brightening)", oneLiner: "Science-led underarm serum for odor + tone.", keywords: ["underarm serum odor brightening", "deodorant serum india", "underarm dark patch serum"], fallbackKeywords: ["deodorant serum india", "underarm dark patch serum"], formatHints: ["serum", "roll-on", "spray"], pricingHints: { trial: [249, 449], monthly: [799, 1399], bundle: [1899, 3199] } },
    { id: "lip-barrier-repair-mask", name: "Lip Barrier Repair Mask (Overnight)", oneLiner: "Overnight lip barrier recovery mask.", keywords: ["lip barrier repair mask", "overnight lip mask india", "fragrance free lip mask"], fallbackKeywords: ["overnight lip mask india", "fragrance free lip mask"], formatHints: ["mask", "balm", "serum"], pricingHints: { trial: [199, 349], monthly: [699, 1199], bundle: [1699, 2799] } },
    { id: "red-light-mini-wand", name: "Red Light Therapy Mini Wand (Budget device)", oneLiner: "Entry red-light device for home routines.", keywords: ["red light therapy mini wand", "budget red light device india", "home led wand skin"], fallbackKeywords: ["budget red light device india", "home led wand skin"], formatHints: ["device", "kit", "serum pair"], pricingHints: { trial: [999, 1999], monthly: [0, 0], bundle: [2499, 5999] } },
    { id: "shower-filter-hard-water", name: "Shower Filter Add-on (Hard water hair fix)", oneLiner: "Simple shower add-on for hard-water damage.", keywords: ["shower filter hard water hair", "hard water hairfall filter", "bath filter india hair"], fallbackKeywords: ["hard water hairfall filter", "bath filter india hair"], formatHints: ["filter", "kit", "cartridge"], pricingHints: { trial: [799, 1499], monthly: [0, 0], bundle: [1999, 4499] } },
    { id: "sensitive-skin-starter-kit", name: "No-Fragrance Sensitive Skin Starter Kit", oneLiner: "Starter protocol for reactive skin users.", keywords: ["fragrance free skincare kit", "sensitive skin starter kit india", "barrier repair starter routine"], fallbackKeywords: ["sensitive skin starter kit india", "barrier repair starter routine"], formatHints: ["kit", "serum", "cream"], pricingHints: { trial: [499, 899], monthly: [1499, 2999], bundle: [3599, 5999] } },
  ],
  "Healthy Snacking": [
    { id: "protein-breakfast-cups", name: "Protein Indian Breakfast Cups (Poha/Upma high protein)", oneLiner: "Instant breakfast cups with better macros.", keywords: ["high protein poha cup", "protein upma cup", "instant high protein breakfast india"], fallbackKeywords: ["protein upma cup", "instant high protein breakfast india"], formatHints: ["cups", "sachets", "bowls"], pricingHints: { trial: [149, 249], monthly: [999, 1799], bundle: [2299, 3999] } },
    { id: "low-sugar-mithai-trial-box", name: "Festival \"Low Sugar Mithai\" Trial Box (Sampler)", oneLiner: "Sampler box for festive low-sugar demand.", keywords: ["low sugar mithai box", "diabetic mithai sampler", "festival sugar free sweets india"], fallbackKeywords: ["diabetic mithai sampler", "festival sugar free sweets india"], formatHints: ["box", "bites", "laddoo"], pricingHints: { trial: [299, 599], monthly: [0, 0], bundle: [1499, 3499] } },
    { id: "prebiotic-fiber-gummies", name: "Prebiotic Fiber Gummies (Snackable gut fiber)", oneLiner: "Easy daily fiber in gummy format.", keywords: ["prebiotic fiber gummies", "phgg gummies india", "gut fiber gummy"], fallbackKeywords: ["phgg gummies india", "gut fiber gummy"], formatHints: ["gummies", "chews", "sachets"], pricingHints: { trial: [199, 349], monthly: [799, 1399], bundle: [1899, 3199] } },
    { id: "electrolyte-gummies", name: "Electrolyte Gummies (Heat + Gym)", oneLiner: "Portable electrolyte top-up for heat days.", keywords: ["electrolyte gummies india", "summer hydration gummies", "gym electrolyte gummies"], fallbackKeywords: ["summer hydration gummies", "gym electrolyte gummies"], formatHints: ["gummies", "chews", "shots"], pricingHints: { trial: [149, 299], monthly: [699, 1199], bundle: [1699, 2799] } },
    { id: "high-protein-dahi-mix", name: "High-Protein Dahi Mix Sachets (Instant)", oneLiner: "Protein add-in for quick dahi bowls.", keywords: ["high protein dahi mix", "instant protein curd mix", "protein yogurt sachet india"], fallbackKeywords: ["instant protein curd mix", "protein yogurt sachet india"], formatHints: ["sachets", "mix", "single sticks"], pricingHints: { trial: [149, 249], monthly: [799, 1499], bundle: [1899, 3299] } },
    { id: "low-gi-laddoo-bite", name: "Glucose-Friendly Laddoo (Low GI meal bite)", oneLiner: "Portable low-GI laddoo for controlled energy.", keywords: ["low gi laddoo", "glucose friendly snack india", "diabetic laddoo protein"], fallbackKeywords: ["glucose friendly snack india", "diabetic laddoo protein"], formatHints: ["laddoos", "bars", "bites"], pricingHints: { trial: [199, 349], monthly: [899, 1599], bundle: [2199, 3699] } },
    { id: "seed-crunch-mineral-bars", name: "Seed Crunch \"Mineral Bars\"", oneLiner: "Seed-forward bars with mineral story.", keywords: ["seed mineral bars", "pumpkin flax bar india", "high mineral snack bar"], fallbackKeywords: ["pumpkin flax bar india", "high mineral snack bar"], formatHints: ["bars", "clusters", "bites"], pricingHints: { trial: [149, 249], monthly: [899, 1599], bundle: [2099, 3599] } },
    { id: "protein-chutney-powder", name: "Protein Chutney Powder (India-native add-on protein)", oneLiner: "Daily meals add-on with protein boost.", keywords: ["protein chutney powder", "high protein podi", "meal add on protein india"], fallbackKeywords: ["high protein podi", "meal add on protein india"], formatHints: ["powder", "sachets", "jar"], pricingHints: { trial: [149, 299], monthly: [699, 1299], bundle: [1699, 2999] } },
  ],
  "Mental Health & Sleep": [
    { id: "sleep-breathing-kit", name: "Mouth Tape + Nasal Strip \"Sleep Breathing Kit\"", oneLiner: "Bundle for better overnight breathing quality.", keywords: ["mouth tape sleep kit", "nasal strip sleep india", "sleep breathing kit"], fallbackKeywords: ["nasal strip sleep india", "sleep breathing kit"], formatHints: ["kits", "patches", "strips"], pricingHints: { trial: [299, 499], monthly: [899, 1499], bundle: [1999, 3299] } },
    { id: "weighted-eye-mask-cooling", name: "Weighted Eye Mask \"Cooling\" Edition", oneLiner: "Cooling pressure mask for faster wind-down.", keywords: ["weighted eye mask cooling", "sleep eye mask weighted india", "cooling sleep mask"], fallbackKeywords: ["sleep eye mask weighted india", "cooling sleep mask"], formatHints: ["masks", "kits", "accessories"], pricingHints: { trial: [399, 699], monthly: [0, 0], bundle: [999, 2299] } },
    { id: "melatonin-free-glycine-gummies", name: "Melatonin-Free Sleep Gummies (Glycine focus)", oneLiner: "Sleep gummies for users avoiding melatonin.", keywords: ["melatonin free sleep gummies", "glycine sleep gummy", "sleep gummy india no melatonin"], fallbackKeywords: ["glycine sleep gummy", "sleep gummy india no melatonin"], formatHints: ["gummies", "strips", "sachets"], pricingHints: { trial: [249, 399], monthly: [799, 1399], bundle: [1999, 3199] } },
    { id: "calm-patch-wearables", name: "Calm Patch Wearables (Stress)", oneLiner: "Daytime stress-support wearable patch.", keywords: ["calm patch wearable", "stress patch india", "anxiety wearable patch"], fallbackKeywords: ["stress patch india", "anxiety wearable patch"], formatHints: ["patches", "kits", "wearables"], pricingHints: { trial: [299, 499], monthly: [999, 1699], bundle: [2299, 3799] } },
    { id: "screen-recovery-kit", name: "Blue-Light \"Screen Recovery\" Kit", oneLiner: "Eye + sleep recovery kit for high screen users.", keywords: ["blue light recovery kit", "screen fatigue sleep kit", "digital eye strain sleep"], fallbackKeywords: ["screen fatigue sleep kit", "digital eye strain sleep"], formatHints: ["kits", "masks", "glasses"], pricingHints: { trial: [499, 899], monthly: [1299, 2299], bundle: [2999, 4999] } },
    { id: "breathwork-hrv-starter", name: "Breathwork + HRV Starter Pack", oneLiner: "Guided breathing starter with HRV-first framing.", keywords: ["breathwork hrv starter", "hrv breathing app bundle", "stress hrv pack"], fallbackKeywords: ["hrv breathing app bundle", "stress hrv pack"], formatHints: ["kits", "app bundle", "accessory"], pricingHints: { trial: [399, 799], monthly: [999, 1999], bundle: [2499, 4599] } },
    { id: "digital-detox-weekend-box", name: "Digital Detox Weekend Box", oneLiner: "Weekend ritual box for attention reset.", keywords: ["digital detox kit", "dopamine detox weekend box", "screen break wellness box"], fallbackKeywords: ["dopamine detox weekend box", "screen break wellness box"], formatHints: ["boxes", "kits", "cards"], pricingHints: { trial: [499, 899], monthly: [0, 0], bundle: [1499, 3499] } },
    { id: "caffeine-free-focus-chews", name: "Caffeine-Free Focus Chews (L-theanine + Tyrosine)", oneLiner: "Focus chews with no caffeine crash.", keywords: ["caffeine free focus chews", "l theanine tyrosine chew", "focus gummies no caffeine"], fallbackKeywords: ["l theanine tyrosine chew", "focus gummies no caffeine"], formatHints: ["chews", "gummies", "strips"], pricingHints: { trial: [249, 399], monthly: [799, 1499], bundle: [1999, 3399] } },
  ],
  "Sports Nutrition": [
    { id: "electrolyte-gel-shots", name: "Electrolyte Gel Shots (Running/Cycling)", oneLiner: "Race-day hydration energy gel shots.", keywords: ["electrolyte gel shots", "running electrolyte gel india", "cycling hydration gel"], fallbackKeywords: ["running electrolyte gel india", "cycling hydration gel"], formatHints: ["gels", "shots", "sachets"], pricingHints: { trial: [199, 349], monthly: [999, 1799], bundle: [2299, 3999] } },
    { id: "intra-workout-ors-2", name: "Intra-Workout Hydration \"ORS 2.0\"", oneLiner: "Performance hydration beyond sugar-heavy ORS.", keywords: ["intra workout hydration ors", "performance ors india", "electrolyte intra workout mix"], fallbackKeywords: ["performance ors india", "electrolyte intra workout mix"], formatHints: ["intra hydration", "sachets", "tubs"], pricingHints: { trial: [249, 399], monthly: [899, 1599], bundle: [2199, 3699] } },
    { id: "creatine-gummies-daily", name: "Creatine Gummies (Daily)", oneLiner: "Convenient creatine for daily adherence.", keywords: ["creatine gummies india", "daily creatine gummy", "creatine chew"], fallbackKeywords: ["daily creatine gummy", "creatine chew"], formatHints: ["gummies", "sachets", "capsules"], pricingHints: { trial: [249, 399], monthly: [899, 1599], bundle: [2199, 3699] } },
    { id: "protein-coffee-shot", name: "Protein Coffee Shot (Pre/Post)", oneLiner: "Small-format protein + coffee shot.", keywords: ["protein coffee shot", "pre workout protein coffee", "post workout coffee protein"], fallbackKeywords: ["pre workout protein coffee", "post workout coffee protein"], formatHints: ["shots", "rtd", "mix sachet"], pricingHints: { trial: [99, 169], monthly: [1199, 2199], bundle: [2799, 4599] } },
    { id: "plant-protein-lite-women", name: "Plant Protein \"Lite\" Blend for Women", oneLiner: "Light digestion protein blend for women.", keywords: ["plant protein lite women", "pea rice protein women india", "easy digest plant protein"], fallbackKeywords: ["pea rice protein women india", "easy digest plant protein"], formatHints: ["powder", "sachets", "ready mix"], pricingHints: { trial: [299, 499], monthly: [1499, 2499], bundle: [3499, 5599] } },
    { id: "recovery-sleep-stack-athletes", name: "Recovery Sleep Stack for Athletes", oneLiner: "Night recovery stack for training adaptation.", keywords: ["athlete recovery sleep stack", "sports sleep supplement", "gym recovery sleep formula"], fallbackKeywords: ["sports sleep supplement", "gym recovery sleep formula"], formatHints: ["capsules", "sachets", "strip-films"], pricingHints: { trial: [299, 499], monthly: [999, 1699], bundle: [2499, 3999] } },
    { id: "joint-collagen-chews", name: "Joint Support Collagen Chews", oneLiner: "Joint support chew for runner and lifting loads.", keywords: ["joint collagen chews", "runner joint support collagen", "sports collagen chew"], fallbackKeywords: ["runner joint support collagen", "sports collagen chew"], formatHints: ["chews", "sachets", "powder"], pricingHints: { trial: [299, 499], monthly: [1099, 1899], bundle: [2599, 4299] } },
    { id: "caffeine-free-preworkout-pump", name: "Caffeine-Free Preworkout \"Pump Mix\"", oneLiner: "Stim-free pump formula for late sessions.", keywords: ["caffeine free preworkout pump", "stim free pre workout india", "pump mix no caffeine"], fallbackKeywords: ["stim free pre workout india", "pump mix no caffeine"], formatHints: ["preworkout", "sachets", "tubs"], pricingHints: { trial: [249, 399], monthly: [899, 1599], bundle: [2199, 3699] } },
  ],
};


